### ISSUE TITLE
Error when trying to retrieve player infos

### ISSUE THREAD

**Issue by MrXetox** [Fabricio-191/valve-server-query#5]
Hi, i was making a discord bot with this library to check my server's stats but when I try to get the players informations with server.getPlayers(), I get this error :

```C:\Users\mrxet\Desktop\Bot\Yoh\node_modules\@fabricio-191\valve-server-query\lib\utils\parsers.js:93
                if(stringEndIndex === -1) throw new Error('string not terminated');
                                                ^

Error: string not terminated
    at BufferParser.string (C:\Users\mrxet\Desktop\Bot\Yoh\node_modules\@fabricio-191\valve-server-query\lib\utils\parsers.js:93:35)
    at Object.playersInfo (C:\Users\mrxet\Desktop\Bot\Yoh\node_modules\@fabricio-191\valve-server-query\lib\utils\parsers.js:230:17)
    at Server.getPlayers (C:\Users\mrxet\Desktop\Bot\Yoh\node_modules\@fabricio-191\valve-server-query\lib\main\server.js:68:18)
    at async C:\Users\mrxet\Desktop\Bot\Yoh\src\events\ready.js:45:27
```

Here's my code : 
```javascript
client.on("ready", async () => {

  const server = await Server({
    ip: "IP",
    port: 27015,
    timeout: 5000,
  });

  console.log(await server.getPlayers());

}); 
```

**Comment by Fabricio-191** [comment]
Is the error consistent ? i tested some random servers and it works fine, if the error is always happening in one server it may be a problem of only that server

You could send me the IP of the server or if you dont want to share the IP you could enable debug mode adding `debug: true` to the server options and showing me what comes out in console

**Comment by MrXetox** [comment]
I tried on 3 randoms servers, i got this error with two of them, and the last one, it returned nothing 🤷🏻‍♂️

**Comment by Fabricio-191** [comment]
I was looking at it and the server gives the package with the users well up to a certain point, then the data it sends does not make sense, it's probably a problem from the server engine

The response with the players info has a number of how many players are in the server, as well as the getInfo response, but the values ​​given in the players info changes, sometimes they were the same sometimes smaller

The problem here is not from my module, the server is wrongly assembling the packet before sending it.

**Comment by Fabricio-191** [comment]
@MrXetox I was reviewing this and i can say with all confidence that this server has multipacket responses completely messed up
I will left some logs with observations here for future references

[debug1.log](https://github.com/Fabricio-191/valve-server-query/files/10322437/debug1.log)
[debug2.log](https://github.com/Fabricio-191/valve-server-query/files/10322438/debug2.log)
