### ISSUE TITLE
rcon.destroy() causes an error

### ISSUE THREAD

**Issue by Mikerosoft25** [Fabricio-191/valve-server-query#8]
Hello, 

I am using your RCON implementation to connect to a Squad Server and execute a command to receive the next map. The connection works perfectly fine and I am able to receive the RCON response.
But if I use `rcon.destroy()` to close the RCON connection I receive an error.

This is a small code example that will result in the error:

```js
import ServerQuery from "@fabricio-191/valve-server-query";

console.log("Connecting via RCON...");

const rcon = await ServerQuery.RCON({
   ip: "127.0.0.1",
   port: 12345,
   password: "xxxxxxxxxxxx",
 });

console.log("Connected.");

const response = await rcon.exec("ShowNextMap");
console.log(`RCON-Response: ${response}`);

console.log("Destroying the connection...");
rcon.destroy();
```

This is the output of the above code with the thrown error:

```
Connecting via RCON...
Connected.
RCON-Response: Next level is Al Basrah, layer is Al Basrah Invasion v1
Destroying the connection...
C:\path\@fabricio-191\valve-server-query\lib\main\RCON.js:188
                this.connection.client.removeAllListeners();
                         ^
TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
```

Could you please check if you can reproduce the same error or am I doing something wrong in the above code?

Thanks in advance!

**Comment by Fabricio-191** [comment]
Solved on version 4.1.9 👍
